services:
  backend:
    image: linkedin-job-searcher-backend:latest
    ports:
      - "4002:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: linkedin-job-searcher-frontend:latest
    ports:
      - "8922:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://linkedin-api.andrepaiva.dev
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
